import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import fs from "fs"
import path from "path"
import matter from "gray-matter"
import ArticleCard from "/components/articlecard"

export default function Articles({ posts }) {
    return (
        <div className="articles">
            <Head>
                <title>Articles</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="pagecontainer">
                {posts.map((post, index) => (
                    <ArticleCard post={post} key={post.slug} />
                ))}
            </div>
        </div>
    )
}

export async function getStaticProps() {
    // Get files from the posts directory
    const files = fs.readdirSync(path.join("posts"))
    // Get slkuf and frontmatter from posts
    const posts = files.map((filename) => {
        // Create slug and replace .md extension
        const slug = filename.replace(".md", "")
        // Get frontmatter (Content of the MD)
        const markdownWithMeta = fs.readFileSync(
            path.join("posts", filename),
            "utf-8"
        )

        const { data: frontmatter } = matter(markdownWithMeta)

        return {
            slug,
            frontmatter,
        }
    })

    return {
        props: { posts: posts },
    }
}
