import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Projects.module.css"
import { useState } from "react"

export default function Projects() {
    return (
        <>
            <Head>
                <title>My projects | Tirso G.</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>potato</main>
        </>
    )
}
